apiVersion: apps/v1
kind: Deployment
metadata:
    name: mydep-empty
spec:
   replicas: 3
   selector:
     matchLabels:
      app: myapp
   template:
      metadata:
        labels:
          app: myapp
      spec:
        containers:
        - name: con1
          image: tomcat:latest
          ports:
          - containerPort: 8080
          volumeMounts:
          - name: myvol
            mountPath: /mydata
        - name: con2
          image: nginx:latest
          ports:
          - containerPort: 80
          volumeMounts:
          - name: myvol
            mountPath: /data 
        volumes:
        - name: myvol
          emptyDir: {}





---
apiVersion: v1
kind: Service
metadata:
  name: mypod
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: myapp

