apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
  namespace: devops
spec:
  limits:
  - default: # this section defines default limits
      cpu: "500m"
      memory: "256Mi"
    defaultRequest: # this section defines default requests
      cpu: "100m"
      memory: "128Mi"
    type: Container
