apiVersion: apps/v1
kind: Deployment
metadata:
    name: mydep-liv-exe
spec:
   replicas: 3
   selector:
     matchLabels:
      app: myapp
   template:
      metadata:
        labels:
          app: myapp
      spec:
        containers:
        - name: con1
          image: tomcat:latest
          ports:
          - containerPort: 8080
        - name: con2
          image: nginx:latest
          ports:
          - containerPort: 80
###### Exec Probe            
#          livenessProbe:
#            exec:
#              command:
#              - cat
#              - /etc/hosts123
#            initialDelaySeconds: 10
#            periodSeconds: 10
####   HTTP Probe ##########
#          livenessProbe:
#             httpGet:
#               path: /
#               port: 80
#             initialDelaySeconds: 10
#             periodSeconds: 10
######### TCP Probe             
          livenessProbe:    
            tcpSocket: 
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10        
---
apiVersion: v1
kind: Service
metadata:
  name: mypod
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: myapp

