---
apiVersion: v1
kind: Pod
metadata:
  name: master-pod
  labels:
    app: mango
spec:
  containers:
  - name: con1
    image: wordpress:latest
    ports:
    - containerPort: 80
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule


