apiVersion: v1
kind: Pod
metadata:
  name: nodeaff-req
  labels:
    app: myapp
spec:
  containers:
  - name: mypod
    image: nginx
    ports:
    - containerPort: 80
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: cpu
            operator: NotIn
            values:
            - ryzen
