apiVersion: v1
kind: Pod
metadata:
  name: nodeaff-pref
  labels:
    app: myapp
spec:
  containers:
  - name: mypod
    image: nginx
    ports:
    - containerPort: 80
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: cpu
            operator: NotIn
            values:
            - ryzen
