---
apiVersion: v1
kind: Pod
metadata:
  name: pod-aff-pref
  labels:
    app: myapp
spec:
  containers:
  - name: con1
    image: wordpress:latest
    ports:
    - containerPort: 80
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - mango
          topologyKey: kubernetes.io/hostname
