---
apiVersion: v1
kind: Pod
metadata:
  name: pod-aff-req
  labels:
    app: myapp
spec:
  containers:
  - name: con1
    image: wordpress:latest
    ports:
    - containerPort: 80
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - mango
        topologyKey: kubernetes.io/hostname
