---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: mypod
spec:
  containers:
  - name: con1
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: myvol
      mountPath: /data
  volumes:
  - name: myvol
    persistentVolumeClaim:
      claimName: myclaim
