apiVersion: v1
kind: Service
metadata:
  name: mypod
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myapp
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: mypod
spec:
  containers:
  - name: con1
    image: wordpress:latest
    ports:
    - containerPort: 80
  - name: con2
    image: mysql:latest
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: test123
    - name: MYSQL_DATABASE
      value: wordpress
    ports:
    - containerPort: 3306
