apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: robodevops
  namespace: devops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: devops
subjects:
- kind: ServiceAccount
  name: robo
  namespace: devops
