---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: mypod
  namespace: devops
spec:
  serviceAccount: robo
  containers:
  - name: con1
    image: nginx:latest
    ports:
    - containerPort: 80
