---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-cm
  labels:
    app: wordpress
spec:
  containers:
  - name: con1
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: myvol
      mountPath: /usr/share/nginx/html/
  volumes:
  - name: myvol
    configMap:
      name: myfile
#    envFrom:
#    - configMapRef:
#       name: mywp
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wordpress
